### ISSUE TITLE
Improvement for `database` & `logger`

### ISSUE THREAD

**Issue by viettd** [wego/pkg#1]
@mysqto suggestions: two small ideas about `pkg` repo:
1. shall we put `db` related pkg in to separated package based on `db` we use, such as `github.com/wego/pkg/database/pgsql`
2. About the `github.com/wego//pkg/logger/request.go`, shall we remove the following parameters https://github.com/wego/pkg/blob/7a16025ddb097832f7515503c95ba2dee0e627a5/logger/request.go#L29-L32 and rename `Request` to `BaseRequest`
```
	PaymentRef      string
	DeploymentRef   string
	ClientCode      string
	TransactionRef  string
```

I think these four are `payments` only

**Comment by mysqto** [comment]
Fixed
